### PR TITLE
path fixes

### PR DESCRIPTION
**Pull request by brucelane**
for imgui

### CODE REVIEW

**Comment by brucelane** [comment]
I had to use this fork https://github.com/DomAmato/ofxVideoRecorder to compile on Windows

**Comment by Daandelange** [comment]
Thanks! :)
Did you get it to compile ?

**Comment by brucelane** [comment]
yes it compiles and runs!

**Comment by Daandelange** [comment]
Merged and updated clone_addons.sh to match the right ofxVideoRecorder fork

**Pull request merged**
